[build]
builder = "nixpacks"
buildCommand = "npm install && python3 -m pip install -r requirements.txt"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[deploy]
startCommand = "node index.js"
restartPolicyType = "always"
